### ISSUE TITLE
Multiple executors on the same node can have conflicting docker images.

### ISSUE THREAD

**Issue by sdquiring** [ROCmSoftwarePlatform/rocJenkins#30]
We need to either use

    image = docker.build(...)

or include the executor id in the docker image name.

The first method may not work due to https://issues.jenkins-ci.org/browse/JENKINS-44836 , but people are reporting that they are getting it to work on that ticket.

**Comment by amdkila** [comment]
Included executor ID in the docker image name here:  https://github.com/ROCmSoftwarePlatform/rocJenkins/commit/9ff43e3bf9ff072855c3651f8a471dc70ac44a46
